# ============================================================
# Ansible Inventory - Using Azure Key Vault
# ============================================================

[mysql_servers]
azure-vm ansible_host=cis-mysql-vm ansible_user=azureuser ansible_password='Azure123!' ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[mysql_servers:vars]
ansible_python_interpreter=/usr/bin/python3
